# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Civic Tech Weekly
tagline:             Your weekly dose of Civic Technology news.
url:                 http://civic-tech-weekly.com
paginate:            2
baseurl:             ""
gems:                [jekyll-paginate]
markdown:            kramdown

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Civic Tech Weekly
  url:               https://twitter.com/civictechweekly

